import React from "react";
import Head from "next/head";
import { Container } from "@mui/material";
import NavBarComponent from "./NavBarComponent";
import FooterComponent from "./FooterComponent";

const Layout = (props) => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBarComponent />
      {props.children}
      <FooterComponent />
    </React.Fragment>
  );
};

export default Layout;
